Repository Vero-Ventures/transaction-classification-bot, pull requests merged in 2024-05, with the labels that each got.

#7 NextJS Initial Project
  .gitignore
  frontend/.eslintrc.json
  frontend/.gitignore
  frontend/README.md
  frontend/app/favicon.ico
  frontend/app/globals.css
  frontend/app/layout.tsx
  frontend/app/page.tsx
  frontend/next.config.mjs
  frontend/package.json
  frontend/postcss.config.mjs
  frontend/public/next.svg
  frontend/public/vercel.svg
  frontend/tailwind.config.ts
  frontend/tsconfig.json
Labels: good first issue

#16 Feature/quickbooks authentication
  .gitignore
  frontend/app/api/auth/[...nextauth]/options.ts
  frontend/app/api/auth/[...nextauth]/route.ts
  frontend/middleware.ts
  frontend/next-auth.d.ts
  frontend/package.json
Labels: enhancement

#9 Set Up Git Hooks with Pre-Commit for Code Quality and Consistency
  frontend/.eslintrc.json
  frontend/.husky/pre-commit
  frontend/.prettierignore
  frontend/.prettierrc.json
  frontend/eslint.config.mjs
  frontend/package.json
Labels: enhancement

#18 Enable dependabot for dependancy updates
  .github/dependabot.yml
Labels: enhancement

#15 Setting up the SearchEngine
  frontend/.gitignore
  frontend/app/page.tsx
  frontend/components/search-engine.tsx
  frontend/components/users.tsx
  frontend/data/indexTypeSense.js
  frontend/data/users.json
  frontend/lib/typesense-client.ts
  frontend/lib/typesense.ts
  frontend/package.json
Labels: enhancement

#20 docker compose and type sense conf
  .gitignore
  search-engine/data/.gitkeep
  search-engine/docker-compose.yml
  search-engine/typesense-server.ini
Labels: enhancement

#24 Feature/session management
  frontend/app/api/auth/[...nextauth]/options.ts
  frontend/app/api/quickbooks/test/route.ts
  frontend/app/layout.tsx
  frontend/app/test/page.tsx
  frontend/components/signout-button.tsx
  frontend/lib/refreshToken.ts
  frontend/next-auth.d.ts
  frontend/package.json
Labels: enhancement

#28 fixed bugs for refreshing tokens
  frontend/app/api/auth/[...nextauth]/options.ts
  frontend/lib/refreshToken.ts
Labels: bug

#32 Dockerized LLM/FastAPI backend
  backend/Dockerfile
  backend/README.md
  backend/compose.yaml
Labels: enhancement

#42 created the script + added to package.json
  frontend/package.json
  frontend/scripts/fix-jose.js
Labels: bug

#45 Precommit hook and github actions change
  .github/workflows/lint-and-format.yml
  .gitignore
  .pre-commit-config.yaml
  .prettierignore
  .prettierrc.json
  README.md
  backend/README.md
  backend/app/api/dependencies.py
  backend/app/api/routes/generate.py
  backend/app/api/routes/keytest.py
  backend/app/llm/loader.py
  backend/app/main.py
  backend/app/test.py
  frontend/.eslintrc.json
  frontend/.husky/pre-commit
  frontend/app/api/auth/[...nextauth]/route.ts
  frontend/app/api/quickbooks/test/route.ts
  frontend/app/globals.css
  frontend/app/layout.tsx
  frontend/app/page.tsx
  frontend/app/test/page.tsx
  frontend/components/search-engine.tsx
  frontend/components/signout-button.tsx
  frontend/components/users.tsx
  frontend/data/indexTypeSense.js
  frontend/eslint.config.mjs
  frontend/lib/db.ts
  frontend/lib/typesense-client.ts
  frontend/lib/typesense.ts
  frontend/middleware.ts
  frontend/next-auth.d.ts
  frontend/package.json
  frontend/tailwind.config.ts
Labels: bug

#47 Fuzzy search functionality
  .gitignore
  frontend/.gitignore
  frontend/actions/classify.ts
  frontend/app/classify/page.tsx
  frontend/app/page.tsx
  frontend/components/search-engine.tsx
  frontend/data/indexTypeSense.js
  frontend/data/users.json
  frontend/lib/typesense-client.ts
  frontend/lib/typesense.ts
  frontend/package.json
  frontend/types/Transaction.ts
  search-engine/data/.gitkeep
  search-engine/docker-compose.yml
  search-engine/typesense-server.ini
Labels: enhancement

#54 added checks to ensure only valid categories are returned
  .gitignore
  frontend/actions/classify.ts
  frontend/app/classify/page.tsx
Labels: bug

#56 37 create transactions page
  backend/README.md
  backend/app/test.py
  frontend/app/classify/page.tsx
  frontend/app/home/page.tsx
  frontend/app/page.tsx
  frontend/components/review.tsx
  frontend/components/selection.tsx
  frontend/types/Transaction.ts
  frontend/utils/filter-transactions.ts
  frontend/utils/format-date.ts
  frontend/utils/format-price.ts
Labels: enhancement

#58 Consistent prettier formatting on files pushed to main
  backend/README.md
  backend/app/api/routes/generate.py
  frontend/actions/customsearch.ts
  frontend/actions/knowledgegraph.ts
  frontend/actions/llm.ts
  frontend/app/api/cse/route.ts
  frontend/app/api/kg/route.ts
  frontend/app/api/llm/batch/route.ts
  frontend/app/api/llm/single/route.ts
  frontend/app/classify/page.tsx
  frontend/app/home/page.tsx
  frontend/components/review.tsx
  frontend/components/selection.tsx
  frontend/components/signout-button.tsx
  frontend/middleware.ts
  frontend/utils/filter-transactions.ts
Labels: bug

#60 fixed toFixed bug
  frontend/utils/format-price.ts
Labels: bug

#71 Play Wright Tests to QA test implemented features
  playwright-tests/.gitignore
  playwright-tests/package.json
  playwright-tests/playwright.config.ts
  playwright-tests/tests/auth.json
  playwright-tests/tests/authhelper.ts
  playwright-tests/tests/config.ts
  playwright-tests/tests/homepage.spec.ts
  playwright-tests/tests/landingpage.spec.ts
  playwright-tests/tsconfig.json
Labels: enhancement

#79 64 update transactions from review page
  frontend/actions/quickbooks.ts
  frontend/app/home/page.tsx
  frontend/components/review.tsx
  frontend/components/selection.tsx
  frontend/lib/refreshToken.ts
Labels: enhancement
